version: '3.7'
services:
  frontend:
    tty: true
    container_name: pxd.co.kr
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0
  firebase-emulators:
    tty: true
    image: andreysenov/firebase-tools
    container_name: firebase-emulators
    user: root
    volumes:
      - ./:/home/node
      - firebase-functions:/home/node/functions/node_modules
    ports:
      - '4000:4000'
      - '5001:5001'
  netlify-cli:
    image: ghcr.io/williamjacksn/netlify-cli
    environment:
      NETLIFY_AUTH_TOKEN: ELar6wh0d1gemjARKZvMnfz1AA4tkjquVRGtVb7vobo
    volumes:
      - ./:/project/
volumes:
  node_modules:
  firebase-functions:
